language: cpp

before_script:
  - hg clone https://hg.libsdl.org/SDL -r release-2.0.8 SDL
  - cd SDL
  - mkdir build
  - cd build
  - ../configure
  - make
  - sudo make install
  - cd ../..

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
