sudo: required

services:
  - docker

language: cpp

before_install:
  - docker run -d --name ubuntu-bionic -v $(pwd):/travis ubuntu:18.04 tail -f /dev/null

install:
  - docker exec -t ubuntu-bionic bash -c "apt-get update && apt-get install -y libsdl2-dev"

script:
  - docker exec -t ubuntu-bionic bash -c "cd /travis && mkdir -p build && cd build && cmake .. && make"

notifications:
    email: false
