language: cpp
dist: bionic

before_install:
  - sudo add-apt-repository universe
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
