language: cpp
dist: xenial
addons:
  apt:
    sources:
    - universe
    packages:
    - libsdl2-dev
    - libegl1-mesa-dev
    - libgles2-mesa-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
