sudo: required

services:
  - docker

language: cpp

before_install:
  - docker run -d --name ubuntu-bionic -v $(pwd):/travis ubuntu:18.04 tail -f /dev/null

install:
  - docker exec -t ubuntu-bionic bash -c "apt-get update && apt-get install -y cmake sudo mercurial;
    hg clone https://hg.libsdl.org/SDL SDL;
    cd SDL;
    mkdir build;
    cd build;
    ../configure;
    make;
    sudo make install"

script:
  - docker exec -t ubuntu-bionic bash -c "cd /travis && mkdir -p build && cd build && /opt/bin/cmake .. && make"

notifications:
    email: false
