sudo: required

services:
  - docker

language: cpp

before_install:
  - docker run -d --name ubuntu-bionic -v $(pwd):/travis ubuntu:18.04 tail -f /dev/null

install:
  - docker exec -t ubuntu-bionic bash -c "apt-get update && apt-get install -y libsdl2-dev;
    wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh;
    sudo sh cmake-3.12.1-Linux-x86_64.sh --skip-license --prefix=/opt"

script:
  - docker exec -t ubuntu-bionic bash -c "cd /travis && mkdir -p build && cd build && /opt/bin/cmake .. && make"

notifications:
    email: false
