name: build

on:
  push:
    branches:
      - master
  pull_request:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  linux:
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
        - compiler: gcc
          cc: gcc-10
          cxx: g++-10
        - compiler: clang
          cc: clang-12
          cxx: clang++-12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libgl1-mesa-glx cmake
    - name:
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        /usr/bin/cmake -S . -B build -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        /usr/bin/cmake --build build -j8
    
    - uses: actions/upload-artifact@v3
      with:
        name: HelloWorld-binary (${{ matrix.compiler }})
        path: build/Samples/HelloWorld

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        cmake --build build -j8
    
    - uses: actions/upload-artifact@v3
      with:
        name: HelloWorld-binary (win)
        path: build/Samples/Debug/HelloWorld.exe
