name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get remove cmake
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libgl1-mesa-glx cmake
        echo $PATH
        whereis cmake
        sudo apt show cmake
        dpkg-query -L cmake
        apt-cache policy cmake
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
