name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libgl1-mesa-glx cmake
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
    - name: build
      run: |
        /usr/bin/cmake -S . -B build
        /usr/bin/cmake --build build -j8

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cmake -S . -B build
        cmake --build build -j8
