name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libgl1-mesa-glx libsdl2-dev
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
