name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
  strategy:
    matrix:
      compiler: [gcc, clang]
      include:
       - compiler: gcc
         cc: gcc-10
         cxx: g++-10
       - compiler: clang
         cc: clang-12
         cxx: clang++-12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libgl1-mesa-glx cmake
    - name:
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        /usr/bin/cmake -S . -B build
        /usr/bin/cmake --build build -j8

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cmake -S . -B build
        cmake --build build -j8
